# Generated by Django 3.2 on 2022-09-23 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['alias'], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
