# Generated by Django 3.2 on 2022-09-23 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('books', '0003_alter_book_author'),
        ('genders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='books',
            field=models.ManyToManyField(related_name='books', to='books.Book'),
        ),
        migrations.CreateModel(
            name='AuthorGender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genders.gender')),
            ],
            options={
                'verbose_name': 'AuthorGender',
                'verbose_name_plural': 'AuthorGenders',
                'ordering': ['gender'],
            },
        ),
    ]
