# Generated by Django 3.2 on 2022-09-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('genders', '0002_auto_20220923_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='authors',
            field=models.ManyToManyField(through='genders.AuthorGender', to='authors.Author'),
        ),
    ]
